[project]
name = "lineup"
version = "0.1.0"
description = "Cross-platform desktop application for managing duplicate and similar photos"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.0",
    "pillow>=10.0.0",
    "pandas>=2.0.0",
]
